// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/admin/post.jsx";
import * as $2 from "./routes/admin/post/[name]/[id].jsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.jsx";
import * as $6 from "./routes/logout.jsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/admin/post.jsx": $1,
    "./routes/admin/post/[name]/[id].jsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.jsx": $5,
    "./routes/logout.jsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
